GAME_TITLE = "Colors hidden in the Snow"
TILE_SIZE = 32
NB_TILES_HORIZONTAL = 40
NB_TILES_VERTICAL = 25
SCREEN_WIDTH = TILE_SIZE * NB_TILES_HORIZONTAL
SCREEN_HEIGHT = TILE_SIZE * NB_TILES_VERTICAL
LOOPS_LIMIT = 300
TIME_PER_MSG = 2
